#!/usr/bin/env python
# coding: utf-8

# In[1]:
import h5py    
import numpy as np 
#from pyjet import cluster,DTYPE_PTEPM
import fastjet
import pandas as pd
import awkward as ak
import vector

# In[2]:

signal_region = (3150, 3850)


# In[3]:


out_names = ['/beegfs/u/bbd1146/daten/events_b_br.h5', '/beegfs/u/bbd1146/daten/events_b_sr.h5', '/beegfs/u/bbd1146/daten/events_s_br.h5', '/beegfs/u/bbd1146/daten/events_s_sr.h5']


# In[4]:


fnew = pd.read_hdf("/beegfs/u/bbd1146/daten/events_anomalydetection.h5")


# In[5]:


events_combined = fnew.T


# In[6]:


np.shape(events_combined)


# In[7]:


n_pf = np.shape(events_combined)[1]


# In[8]:


# Create arrays for the PFCands for the first and the second jet
j1pf = np.zeros((n_pf, 300), np.float16)
j2pf = np.zeros((n_pf, 300), np.float16)

# an array for the jet kinematics variables
# 14 floats. Mjj, delta_eta (between j1 and j2), followed by the 4 vectors of j1, j2 and j3 in pt,eta,phi,m_softdrop format (if no 3rd jet passing cuts, zeros)
jet_kinematics = np.zeros((n_pf, 14), np.float64)


# In[9]:

vector.register_awkward()
jetdef = fastjet.JetDefinition(fastjet.antikt_algorithm, 1.0)
for i in range(n_pf):
    if (i%1000==0):
        print('> computed ' + str(i) + ' events')
    
    event = events_combined[i]
    pts, etas, phis = [], [], []
    for j in range(700):
        pT  = event[j * 3]
        eta = event[j * 3 + 1]
        phi = event[j * 3 + 2]
        if pT > 0:
            pts.append(pT)
            etas.append(eta)
            phis.append(phi)

    # Awkward Array with pt/eta/phi/M 
    array = ak.Array(
        {"pt": pts, "eta": etas, "phi": phis, "M": [0.0] * len(pts)},
        with_name="Momentum4D",
    )

    # Clustering
    cluster = fastjet.ClusterSequence(array, jetdef)
    jets = cluster.inclusive_jets(min_pt=0)          
    jets = jets[ak.argsort(jets.pt, ascending=False)] #pT sort


    if len(jets) > 1:
        E = jets[0].energy + jets[1].energy
        px = jets[0].px + jets[1].px
        py = jets[0].py + jets[1].py
        pz = jets[0].pz + jets[1].pz
        jet_kinematics[i, 0] = (E**2-px**2-py**2-pz**2)**0.5  # calculate mjj
    
    n_jets_save = np.min([len(jets), 3])  # save values for the first 3 jets if 3 jets exist
    for j in range(n_jets_save):
        vec = np.array([jets[j].pt, jets[j].eta, jets[j].phi, jets[j].mass])  # the 4 vector of the jet
        jet_kinematics[i, 2+j*4 : 2+(j+1)*4] = vec
        
        if j < 2:
            consts = cluster.constituents()[j]
            
            pf_cands = np.array([
                ak.to_numpy(consts.pt),
                ak.to_numpy(consts.eta),
                ak.to_numpy(consts.phi)
            ]).T.flatten()  # shape: (N*3,)

            len_pf = min(len(pf_cands), 300)

            # insert the PFCands in the j1pf or j2pf array
            if j == 0:
                j1pf[i, :len_pf] = pf_cands[:len_pf]
            if j == 1:
                j2pf[i, :len_pf] = pf_cands[:len_pf]

# In[10]:


jet_kinematics[:, 1] = np.abs(jet_kinematics[:, 3] - jet_kinematics[:, 7])  # calculate Delta eta


# In[11]:


issignal = np.zeros((n_pf, 1), dtype = np.int8)
issignal[:, 0] = fnew.iloc[:, 2100]


# In[12]:


groups = []

groups.append(((jet_kinematics[:, 0] < signal_region[0]) | (jet_kinematics[:, 0] > signal_region[1])) & (issignal.reshape(-1) == 0))  # B in BR
groups.append((jet_kinematics[:, 0] >= signal_region[0]) & (jet_kinematics[:, 0] <= signal_region[1]) & (issignal.reshape(-1) == 0))  # B in SR

groups.append(((jet_kinematics[:, 0] < signal_region[0]) | (jet_kinematics[:, 0] > signal_region[1])) & issignal.reshape(-1))  # S in BR
groups.append((jet_kinematics[:, 0] >= signal_region[0]) & (jet_kinematics[:, 0] <= signal_region[1]) & issignal.reshape(-1))  # S in SR


# In[13]:


groups = np.array(groups, dtype = np.bool)
if ((groups.sum(0) != 1).sum()) != 0:
    raise AssertionError('Some elements are in no or more than one group')


# In[14]:


n_ev_gr = groups.sum(1)  # number of events in each group


# In[15]:


orders = []

for i in range(len(groups)):
    order = np.arange(n_ev_gr[i])
    np.random.shuffle(order)
    orders.append(order)
    with open('/beegfs/u/bbd1146/daten/shuffle_order_region_' + str(i) + '.npy', 'wb') as f_order:
        np.save(f_order, order)


# In[16]:


# open the files
out_files = []
for name in out_names:
    out_files.append(h5py.File(name, 'w'))


# In[17]:


for i in range(len(groups)):
    j1pf_i = j1pf[groups[i]]  # select the events belonging to the current group
    j1pf_i = j1pf_i[orders[i]]  # sort them in the order of the current group
    out_files[i].create_dataset('jet1_PFCands', data = j1pf_i, chunks = (np.min([n_ev_gr[i], 1000]), 300), compression = 'gzip')  # save the data
    
    j2pf_i = j2pf[groups[i]]  # select the events belonging to the current group
    j2pf_i = j2pf_i[orders[i]]  # sort them in the order of the current group
    out_files[i].create_dataset('jet2_PFCands', data = j2pf_i, chunks = (np.min([n_ev_gr[i], 1000]), 300), compression = 'gzip')  # save the data
    
    issignal_i = issignal[groups[i]]
    issignal_i = issignal_i[orders[i]]
    out_files[i].create_dataset('truth_label', data = issignal_i, compression = 'gzip')
    
    jet_kinematics_i = jet_kinematics[groups[i]]
    jet_kinematics_i = jet_kinematics_i[orders[i]]
    out_files[i].create_dataset('jet_kinematics', data = jet_kinematics_i, chunks = (np.min([n_ev_gr[i], 1000]), 14), compression = 'gzip')


# In[18]:


for out_file in out_files:
    out_keys = out_file.keys()
    print(out_keys)
    for key in out_keys:
        print(key)
        print(out_file[key])
    out_file.close()
